### ISSUE TITLE
As a user, I need to be provided an interface where teams  in the database is listed with their information on of the Scofoot application to have a easy access to the database..

### ISSUE THREAD

**Issue by ruyadinmezel** [SU-CS308-22FA/Team-35-SCOFOOT#42]
##### Acceptence Criteria
-Teams page should be easily accessible.
- For instance, when user opens  the teams page, teams should be listed with their information.
- Corresponding  football club schema should be created.

**Comment by bilgehancoskun** [comment]
Merged with another issue.
